# Generated by Django 5.2.5 on 2025-08-29 22:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10, unique=True)),
                ('aircraft_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField()),
                ('business_seats', models.PositiveIntegerField(default=0)),
                ('economy_seats', models.PositiveIntegerField()),
                ('year_manufactured', models.PositiveIntegerField()),
                ('last_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('grounded', 'Grounded'), ('retired', 'Retired')], default='active', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlightOperationsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_flights', models.PositiveIntegerField(default=0)),
                ('on_time_departures', models.PositiveIntegerField(default=0)),
                ('delayed_flights', models.PositiveIntegerField(default=0)),
                ('cancelled_flights', models.PositiveIntegerField(default=0)),
                ('average_delay_minutes', models.PositiveIntegerField(default=0)),
                ('total_passengers', models.PositiveIntegerField(default=0)),
                ('passenger_satisfaction', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('gate_utilization', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('crew_utilization', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='baggage_allowance',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_baggage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_opted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='meal_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='taxes_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkin',
            name='boarding_pass_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='checkin',
            name='check_in_method',
            field=models.CharField(default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='excess_baggage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='checkin',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='checkin',
            name='security_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='special_assistance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.CharField(default='UNK', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='boarding_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='business_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='check_in_opens',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='delay_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(default='UNK', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='passenger',
            name='frequent_flyer_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='passenger',
            name='mobility_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_expiry',
            field=models.DateField(default=datetime.date(2030, 1, 1)),
        ),
        migrations.AddField(
            model_name='passenger',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.'), ('Prof', 'Prof.')], default='Mr', max_length=10),
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='staff',
            name='flight_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_training',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_certificate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_training_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification_status',
            field=models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('pending', 'Renewal Pending')], default='current', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled'), ('completed', 'Flight Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('boarding_pass_issued', 'Boarding Pass Issued'), ('security_cleared', 'Security Cleared'), ('at_gate', 'At Gate'), ('boarded', 'Boarded'), ('no_show', 'No Show')], default='checked_in', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('copilot', 'Co-Pilot'), ('cabin_crew', 'Cabin Crew'), ('ground_staff', 'Ground Staff'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('dispatcher', 'Flight Dispatcher'), ('gate_agent', 'Gate Agent'), ('customer_service', 'Customer Service'), ('baggage_handler', 'Baggage Handler'), ('admin', 'Administrator')], max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aircraft'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('booking', 'Booking Action'), ('checkin', 'Check-in Action'), ('admin', 'Admin Action')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('portal_used', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.CharField(max_length=10, unique=True)),
                ('terminal', models.CharField(max_length=10)),
                ('gate_type', models.CharField(default='Standard', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned')], default='available', max_length=20)),
                ('next_available', models.DateTimeField(blank=True, null=True)),
                ('current_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gate', to='core.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gate'),
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('affected_system', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_access', models.CharField(choices=[('customer', 'Customer Portal'), ('airline', 'Airline Operations'), ('crew', 'Crew Portal'), ('admin', 'System Admin')], default='customer', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('loyalty_number', models.CharField(blank=True, max_length=20)),
                ('loyalty_tier', models.CharField(default='Silver', max_length=20)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_flight', models.CharField(max_length=50)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('briefing_completed', models.BooleanField(default=False)),
                ('post_flight_report', models.TextField(blank=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
            options={
                'unique_together': {('staff', 'flight')},
            },
        ),
    ]
